# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 6
#$ -q mThC.q
#$ -l mres=24G,h_data=4G,h_vmem=4G
#$ -cwd
#$ -j y
#$ -N SRRxxxx_bowtie2_PROGRAM
#$ -o logs/SRRxxxx_bowtie2_PROGRAM.log

# ----------------Modules------------------------- #
module load tools/conda
start-conda
conda activate /scratch/nmnh_lab/genome_skimming/envs/bowtie2_env
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
bowtie2-build \
/scratch/genomics/USER/PROJECT/data/results/getorganelle/SRRxxxx/CONTIG_FILE.fasta \
/scratch/genomics/USER/PROJECT/data/results/bowtie2/SRRxxxx_bowtie2_PROGRAM/CONTIG_FILE
#
bowtie2 \
-x /scratch/genomics/USER/PROJECT/data/results/bowtie2/SRRxxxx_bowtie2_PROGRAM/CONTIG_FILE \
-1 /scratch/genomics/USER/PROJECT/data/trimmed_sequences/SRRxxxx_R1_PE_trimmed.fastq \
-2 /scratch/genomics/USER/PROJECT/data/trimmed_sequences/SRRxxxx_R2_PE_trimmed.fastq \
-S /scratch/genomics/USER/PROJECT/data/results/data/bowtie2/SRRxxxx_bowtie2_PROGRAM/SRRxxxx_bowtie2_PROGRAM.sam \
-p $NSLOTS

#
echo = `date` job $JOB_NAME done

# bowtie2-build builds an index file from your reference sequence, and saves it
# in the bowtie2 results folder 

# -1 is the path to the file of the paired R1 reads of the first paired-end 
# library (you can have mutiple libraries as input files). 
# -2 is the path to the file of the paired R2 reads of the first paired-end 
# library. 
# -p is the number of threads, and -m is the total amount of memory allocated 
# --tmp-dir creates a temporary SSD to hold SPAdes temporary files. SPAdes 
# creates a large number of temporary files, sometimes more than hydra allows.
# This creates a temporary SSD to hold those files so hydra won't kill the
# job. we then remove those files with rm -rf $SSD_DIR/*