#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThC.q
#$ -l mres=6G,h_data=6G,h_vmem=6G
#$ -cwd
#$ -j y
#$ -N fastqc_raw_LOOP
#$ -o logs/fastqc_raw_LOOP.log
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
conda activate /scratch/nmnh_lab/envs/genome_skimming/fastqc_ksm
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#

# This scripts expects a file to be given as an argument when submitted
# $1 contains the first input argument

if [ -z $1 ]; then
  echo "ERROR: enter the name of the fastq file as argument with qsub."
  echo "   Example: qsub fastqc_raw_LOOP.job ../data/raw/reads_1.fastq"
  echo "...exiting"
  exit 1 
fi

# FASTQ is the name of the fastq file supplied as an argument
FASTQ=$1

#
fastqc \
  $FASTQ \
  -o /scratch/genomics/USER/PROJECT/data/raw

#
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the fastqc
# environment, and runs fastqc on the named read files

# -o is the path to the output directory
