#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThC.q
#$ -l mres=8G,h_data=8G,h_vmem=8G
#$ -cwd
#$ -j y
#$ -N SRRxxxx_fasterq
#$ -o logs/SRRxxxx_fasterq.log
#
# ----------------Modules------------------------- #
module load bioinformatics/sratoolkit
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
#

fasterq-dump /scratch/genomics/USER/PROJECT/data/sra/SRRxxxx \
--outdir /scratch/genomics/USER/PROJECT/data/raw/ \
--threads $NSLOTS


# --outdir is the target directory for your converted read files. --threads is
# number of threads fasterq-dump will use. $NSLOTS tells the program to use the
# number of threads assigned in the Parameters section