#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -q sThC.q
#$ -l mres=6G,h_data=6G,h_vmem=6G
#$ -cwd
#$ -j y
#$ -N SRRxxxx_fastqc
#$ -o logs/SRRxxxx_fastqc.log
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
conda activate /scratch/nmnh_lab/envs/genome_skimming/fastqc_ksm
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#

#
fastqc \
/scratch/genomics/USER/PROJECT/data/raw/SRRxxxx_1.fastq \
-o /scratch/genomics/USER/PROJECT/data/raw


fastqc \
/scratch/genomics/USER/PROJECT/data/raw/SRRxxxx_2.fastq \
-o /scratch/genomics/USER/PROJECT/data/raw

#
echo = `date` job $JOB_NAME done

# This job file loads the conda module, activates the fastqc
# environment, and runs fastqc on the named read files

# -o is the path to the output directory
