#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 8
#$ -q sThC.q
#$ -l mres=8G
#$ -cwd
#$ -j y
#$ -N SAMPLE_fasterq
#$ -o logs/SAMPLE/fasterq.log
#
# ----------------Modules------------------------- #
module load bioinformatics/sratoolkit
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
#

fasterq-dump /scratch/genomics/USER/PROJECT/data/sra/SRRxxxxxxx \
--outdir ${data}scratch/genomics/USER/PROJECT/data/raw/ \
--threads $NSLOTS

mv ${data}/raw/${sample}_1.fastq ${data}/raw/${sample}_R1.fastq
mv ${data}/raw/${sample}_2.fastq ${data}/raw/${sample}_R2.fastq

# --outdir is the target directory for your converted read files. --threads is
# number of threads fasterq-dump will use. $NSLOTS tells the program to use the
# number of threads assigned in the Parameters section