#!/bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 4
#$ -q sThC.q
#$ -l mres=16G,h_data=4G,h_vmem=4G
#$ -cwd
#$ -j y
#$ -N SAMPLE
#$ -o logs/SAMPLE_mitofinder.log
#
# ----------------Modules------------------------- #
module load bioinformatics/mitofinder
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#
#
mitofinder \
-j SAMPLE_mitofinder \
-o 2 \
-r /scratch/nmnh_lab/genome_skimming/ref/MITOREFERENCE \
-a /path_to_fasta_file/SAMPLE.fasta \
--new-genes -p $NSLOTS -m 16

#
echo = `date` job $JOB_NAME done

# -j is the process name, what the job will be called
# -o is the genetic code to use. The list below is from the mitofinder
# documantation (https://github.com/RemiAllio/MitoFinder/blob/master/README.md).
# -r is the path to the reference database, in genbank (.gb) format. Mitofinder
# documentation (https://github.com/RemiAllio/MitoFinder/blob/master/README.md),
# shows how to create a reference database from NCBI.
# -a is the fasta file containing the contigs that mitofinder will use to 
# annotate 
# --new-genes denotes that some of the genes in the reference database are not
# one of the "official" genes as determined by mitofinder. This is often true
# if you have downloaded the reference database from genbank, because there are 
# some mispellings in gene names in genbank.
# -p is the number of threads you have requested
# -m is the amount of RAM you have requested, and it should equal "mres" from the 
# parameters section of the job

# Genetic codes
# 1. The Standard Code 
# 2. The Vertebrate Mitochondrial Code 
# 3. The Yeast Mitochondrial Code 
# 4. The Mold, Protozoan, and Coelenterate Mitochondrial Code and the
#     Mycoplasma/Spiroplasma Code
# 5. The Invertebrate Mitochondrial Code
# 6. The Ciliate, Dasycladacean and Hexamita Nuclear Code 
# 9. The Echinoderm and Flatworm Mitochondrial Code 
# 10. The Euplotid Nuclear Code 
# 11. The Bacterial, Archaeal and Plant Plastid Code 
# 12. The Alternative Yeast Nuclear Code 
# 13. The Ascidian Mitochondrial Code 
# 14. The Alternative Flatworm Mitochondrial Code 
# 16. Chlorophycean Mitochondrial Code 
# 21. Trematode Mitochondrial Code 
# 22. Scenedesmus obliquus Mitochondrial Code 
# 23. Thraustochytrium Mitochondrial Code 
# 24. Pterobranchia Mitochondrial Code 
# 25. Candidate Division SR1 and Gracilibacteria Code

# Using a more limited reference database greatly reduces run time. For exmaple,
# changing from the full database (14000+ mitogenomes) to just molluscs (<500
# mitogenomes) reduces run time from > 3 hours to < 5 minutes, typically.
# Currently there are 11 taxon-specific databases, replace MITOREFERENCE above
# with one of the following databases
: 
# mito_reference_Vertebrata_23Aug23.gb
# mito_reference_Tunicata_21Dec23.gb
# mito_reference_Porifera_10Jan24.gb
# mito_reference_Nemertea_10Jan24.gb
# mito_reference_Mollusca_23Aug23.gb
# mito_reference_Echinodermata_22Dec23.gb
# mito_reference_Ctenophora_10Jan24.gb
# mito_reference_Cnidaria_23Aug23.gb
# mito_reference_Bryozoa_9Jan23.gb
# mito_reference_Arthropoda_23Aug23.gb
# mito_reference_Annelida_23Aug23.gb

# There is one database containing the full Genbank refseq database:
# mito_reference_Metazoa_23Aug23.gb

# If your taxa of interest are not in one of these groups, you can either enter
# "Metazoa" to use the entire database or contact me and I can typically create
# your chosen database in short order.