# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 5
#$ -q mThM.q
#$ -l mres=200G,h_data=40G,h_vmem=40G,himem
#$ -cwd
#$ -j y
#$ -N SRRxxxx_quast_PROGRAM
#$ -o logs/SRRxxxx_quast_PROGRAM.log

# ----------------Modules------------------------- #
module load tools/conda
start-conda
conda activate /scratch/nmnh_lab/genome_skimming/envs/quast_ksm
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#

#
quast.py \
/scratch/genomics/USER/PROJECT/data/results/PROGRAM/SRRxxxx/CONTIG_FILE.fasta \
-o /scratch/genomics/USER/PROJECT/data/results/quast/SRRxxxx_quast_PROGRAM \
--pe1 /scratch/genomics/USER/PROJECT/data/trimmed_sequences/SRRxxxx_R1_PE_trimmed.fastq \
--pe2 /scratch/genomics/USER/PROJECT/data/trimmed_sequences/SRRxxxx_R2_PE_trimmed.fastq \
--single /scratch/genomics/USER/PROJECT/data/trimmed_sequences/SRRxxxx_R0_SE_trimmed.fastq \
-t $NSLOTS

#
echo = `date` job $JOB_NAME done

# -o is the path to the directory where you want your results saved
# --pe1 is the path to the file of the paired R1 reads of the first paired-end 
# library (you can have mutiple libraries as input files). 
# --pe2 is the path to the file of the paired R2 reads of the first paired-end 
# library. 
# --single is the path of the unpaired reads (both R1 and R2 should be in the 
# same file) of the first paired-end library.
# -t is the number of threads
# -m is the total amount of memory allocated 
