# /bin/sh
# ----------------Parameters---------------------- #
#$ -S /bin/sh
#$ -pe mthread 10
#$ -q mThM.q
#$ -l mres=200G,h_data=20G,h_vmem=20G,himem
#$ -cwd
#$ -j y
#$ -N SRRxxxx_quast
#$ -o logs/SRRxxxx_quast.log
#
# ----------------Modules------------------------- #
module load tools/conda
start-conda
conda activate /scratch/nmnh_lab/genome_skimming/envs/quast_ksm
# ----------------Your Commands------------------- #
#
echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME
echo + NSLOTS = $NSLOTS
#

#
quast.py \
/scratch/genomics/USER/PROJECT/data/results/mitogenome/SRRxxxx.fasta
-o /scratch/genomics/USER/PROJECT/data/results/quast/SRRxxxx \
--pe1 /scratch/genomics/USER/PROJECT/data/trimmed_sequencesSRRxxxx_R1_PE_trimmed.fastq.gz \
--pe2 /scratch/genomics/USER/PROJECT/data/trimmed_sequencesSRRxxxx_R2_PE_trimmed.fastq.gz \
--single /scratch/genomics/USER/PROJECT/data/trimmed_sequencesSRRxxxx_R0_SE_trimmed.fastq.gz \
-t $NSLOTS

#
echo = `date` job $JOB_NAME done

# -o is the path to the directory where you want your results saved
# --pe1 is the path to the file of the paired R1 reads of the first paired-end 
# library (you can have mutiple libraries as input files). --pe2 is the path
# to the file of the paired R2 reads of the first paired-end library. --single
# is the path of the unpaired reads (both R1 and R2 should be in the same file)
# of the first paired-end library.
# -t is the number of threads, and -m is the total amount of memory allocated 
# --tmp-dir creates a temporary SSD to hold SPAdes temporary files. SPAdes 
# creates a large number of temporary files, sometimes more than hydra allows.
# This creates a temporary SSD to hold those files so hydra won't kill the
# job. we then remove those files with rm -rf $SSD_DIR/*